### ISSUE TITLE
'Scene' object has no attribute 'get_actors'

### ISSUE THREAD

**Issue by horsto** [brainglobe/bg-brainrender-gui#1] opened 2020-07-31 15:03 UTC
Hi! After pip installing the GUI and trying to launch from terminal (macOS Catalina 10.15.5) I get the following error: 

```
allen mouse atlas (res. 25um)
From: http://www.brain-map.org.com (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
WARNING: Populating font family aliases took 502 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. 
Traceback (most recent call last):
  File "/opt/miniconda3/envs/analysis/bin/brainrender-gui", line 8, in <module>
    sys.exit(clilaunch())
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/__init__.py", line 23, in clilaunch
    ex = App(atlas=atlas, axes=axes)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/app.py", line 43, in __init__
    self._update()
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/app.py", line 402, in _update
    self._update_actors()
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/app.py", line 383, in _update_actors
    for actor in self.scene.get_actors():
AttributeError: 'Scene' object has no attribute 'get_actors'
```

**Comment by FedeClaudi** [comment] 2020-07-31 16:12
Hi, 

Thanks for reporting the bug, it should be fixed now (dd3462103768f053c046497d7840a892cd4709b1).

Can you please try:
```
pip install bg-brainrender-gui  -U
```

to update and let us know if you find any other problem?

Thank you, 
Federico

**Comment by horsto** [comment] 2020-07-31 16:21
Thanks @FedeClaudi for fixing this so quickly! 

The GUI starts and I can see the allen_mouse_25um_v0.3 in 3D, add regions, etc., but I am running into another error when trying to load files ('Add cells' etc.):
`2020-07-31 18:18:30.175 python[12315:4084693] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'com.apple.view-bridge': Connection interrupted
`

Also a warning occurs whenever I try to interact with anything in the GUI (just FYI): 
`WARNING: Cannot open file '/Users/hotte/.brainglobe/allen_mouse_25um_v0.3/meshes/brainrender_gui/icons/eye-slash.svg', because: No such file or directory
`

**Comment by FedeClaudi** [comment] 2020-07-31 19:43
Hi, 

I wasn't able to reproduce the first of the two errors, the `add_cells` functionality works well on my machine (also a mac). I've also never seen that error message nor do I know what could be causing it. 
Could you give me some more details about your setup and when exactly the error shows up?

I will open a separate issue for the icons' warning, it seems to that the images were not packaged with the rest of the code. It shouldn't prevent you from using the app though.

**Comment by horsto** [comment] 2020-08-01 09:38
Thanks, things seem to work after re-initializing everything (terminal, conda env, ... )! I have no idea why that error popped up routinely yesterday. 

I however came across another error when trying to load in a .mat file from sharp track: 
```
Added 28 cells to the scene
WARNING: Traceback (most recent call last):
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/app.py", line 269, in add_from_file_sharptrack
    self.add_from_file(self.scene.add_probe_from_sharptrack)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/app.py", line 252, in add_from_file
    act.alpha(alpha)
AttributeError: 'tuple' object has no attribute 'alpha'
Abort trap: 6

```
Any idea what could have gone wrong there?

**Comment by FedeClaudi** [comment] 2020-08-14 18:08
Hi, 

sorry for the delay in gettin back to you, I was on holiday. 
Are you still having the same issue?

**Comment by horsto** [comment] 2020-08-14 18:13
No worries! I haven't tried again (was hoping there might be something obvious there...). In case you want to test it yourself, I uploaded the probe file matlab export here: https://studntnu-my.sharepoint.com/:f:/g/personal/horsto_ntnu_no/ErXRAWhUAcJInI5tjsK8NpcBtgoeo90Z2ZB5dBni7de8mg?e=2E9EwI

**Comment by FedeClaudi** [comment] 2020-08-14 18:46
That's great thanks!

The bug should be fixed now with 488dbf46395b6ad563b6fa78222d1ec70bbd5a50 [release version `0.0.4`].
To test it: `pip install bg-brainrender-gui -U `

Hope it all works fine, but do let me know if it doesn't

**Comment by horsto** [comment] 2020-08-15 10:34
Hey @FedeClaudi, thanks for fixing this! I was indeed able to import the probe points. However, it seems that the points are not only displayed in the wrong hemisphere (should be left), but they are also in a different area than where I marked them in SHARP (should be inside the blue area), and seem to be 90 degrees rotated in respect to the D-V axis (the little "kink" at the bottom of the line of pink dots should points towards the back of the brain, instead it is pointing outwards (towards lateral)). 
![Screenshot 2020-08-15 at 12 28 35](https://user-images.githubusercontent.com/7548928/90310577-fd385200-def2-11ea-8135-df59fbf7bbbe.png)

Sorry for keeping you busy here, but do you think that is an error accumulating in SHARP track or in your GUI?

**Comment by FedeClaudi** [comment] 2020-08-15 11:28
mmm, that's weird. The code to load the sharptrack data in brainrender hasn't changed since it was first developed and it worked fine so far. 

I've tested it on the data I got when this function was added (I never used sharptrack myself): https://github.com/BrancoLab/BrainRender/issues/44

It still works fine on those data but it seems rotated in yours. Might it be something wrong with how the data were processed?

**Comment by horsto** [comment] 2020-08-15 11:45
Ok, I will dig a bit deeper. I only quickly tested the combination of sharptrack and brainrender GUI because I want to use it for my data but have actually never used either for anything else before. So maybe the mistake is on my side. I will try again with sharptrack and see if the error is still there. One thing I noticed is that the brainrender GUI refers to `allen_mouse_25um` when loading and the sharptrack data I think is in a 100um (?) reference? Could this play a role in any way?

**Comment by FedeClaudi** [comment] 2020-09-13 18:16
@horsto  as you know the mirroring discussed here was caused with incosistencies in `brainrender`'s axes order (relative to `bg-atlaspi`. This will hopefully be fixed in the [next release of brainrender](https://github.com/BrancoLab/brainrender/issues/104) so I'll close this issue.

**Closed as completed by FedeClaudi** 2020-09-13 18:16 UTC
