### ISSUE TITLE
Problems with newest bg atlases?

### ISSUE THREAD

**Issue by horsto** [brainglobe/bg-brainrender-gui#7] opened 2020-09-06 15:11 UTC
Hi, I am not completely sure what is happening here, but thought I'd just copy and paste the error. This happens while starting `brainrender-gui` (10um atlas is newest version as of today - seems to be a `bg_atlasapi` issue actually?) 
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/analysis/bin/brainrender-gui", line 8, in <module>
    sys.exit(clilaunch())
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/__init__.py", line 36, in clilaunch
    ex = App(atlas=atlas, axes=axes, screenshot_kwargs=screenshot_kwargs)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/app.py", line 36, in __init__
    UI.__init__(self, *args, **kwargs)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/ui.py", line 69, in __init__
    self.initUI()
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/ui.py", line 271, in initUI
    self.treeView = self.make_left_navbar()
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/ui.py", line 118, in make_left_navbar
    name = self.scene.atlas._get_from_structure(node.tag, "name")
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/bg_atlasapi/core.py", line 229, in _get_from_structure
    return self.structures[structure][key]
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/bg_atlasapi/structure_class.py", line 69, in __getitem__
    item = self.acronym_to_id_map[item]
KeyError: 'root (997)'
(analysis) Horsts-MacBook-Pro:brainreg-segment hotte$ brainrender-gui
allen mouse atlas (res. 10um)
From: http://www.brain-map.com (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
Traceback (most recent call last):
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/bg_atlasapi/structure_class.py", line 67, in __getitem__
    item = int(item)
ValueError: invalid literal for int() with base 10: 'root (997)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/analysis/bin/brainrender-gui", line 8, in <module>
    sys.exit(clilaunch())
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/__init__.py", line 36, in clilaunch
    ex = App(atlas=atlas, axes=axes, screenshot_kwargs=screenshot_kwargs)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/app.py", line 36, in __init__
    UI.__init__(self, *args, **kwargs)
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/ui.py", line 69, in __init__
    self.initUI()
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/ui.py", line 271, in initUI
    self.treeView = self.make_left_navbar()
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/brainrender_gui/ui.py", line 118, in make_left_navbar
    name = self.scene.atlas._get_from_structure(node.tag, "name")
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/bg_atlasapi/core.py", line 229, in _get_from_structure
    return self.structures[structure][key]
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/bg_atlasapi/structure_class.py", line 69, in __getitem__
    item = self.acronym_to_id_map[item]
KeyError: 'root (997)'
```

**Comment by vigji** [comment] 2020-09-06 15:18
How exactly are you using it? something that happened in the tree representation of the `Structures` class, ie I changed the tag to contain the name of the structure + the id (so that if you print it you can consult both the hierarchy and some sort of structure id lookup table).
So in that line you should amend that line in `brainrender_gui` to parse strip the brackets containing the region id if you want to use the region tree `tag`. Otherwise, we go back to the version with only the name as tag @FedeClaudi , but I liked it with the number as well!

**Comment by FedeClaudi** [comment] 2020-09-06 15:32
I don't mind either way though if it's something that it's used frequently it might be a bit annoying to parse the string. Can it return stuff as a tuple so that it's easier to select what to use?

**Comment by vigji** [comment] 2020-09-06 16:39
The reason why that is the case is that I thought that “tag” is more of a lengthy description of the mode, while the Univoke identifier is something like node.id - we should probably be using that I think

**Comment by FedeClaudi** [comment] 2020-09-06 17:09
Okay, I don't mind either way. Just once we've decided for one thing we'll have to fix this issue. In the meanwhile downgrading to a previous version of the atlas api should fix things

**Comment by vigji** [comment] 2020-09-07 06:49
I now made a small bugfix for this in #8. Then, if you don't mind for keep things consistent  we should use the `node.identifier` to go from tree to structures dictionary, and keep the `node.tag` just for labels/printing

**Comment by FedeClaudi** [comment] 2020-09-13 18:14
This should be fixed now. @horsto  can you confirm please?

**Comment by horsto** [comment] 2020-09-13 18:52
I'm trying to check it but building from the latest commit runs into weird pandas version conflicts for me. 
`pkg_resources.ContextualVersionConflict: (pandas 0.25.2 (/opt/miniconda3/envs/analysis/lib/python3.6/site-packages), Requirement.parse('pandas>=1.0.5'), {'neurom'})
`
while trying to install pandas >=1.05 runs into: 
`pkg_resources.ContextualVersionConflict: (pandas 1.1.2 (/opt/miniconda3/envs/analysis/lib/python3.6/site-packages), Requirement.parse('pandas<=0.25.3,>=0.25.1'), {'allensdk'})`

I'll have a closer look tomorrow.

**Comment by FedeClaudi** [comment] 2020-09-13 19:42
>  latest commit 

in brainrender? Installing the latest brainrender worked for me...  I haven't tested the GUI with the development branch of brainrender though. 

Or did you mean the PR I've merged here?

**Comment by horsto** [comment] 2020-09-14 06:48
I meant the PR you merged here. I tried to install brainrender from scratch and I am now on version `brainrender-1.0.0.0`.
`Neurom` requires a later pandas version (`error: pandas 0.25.3 is installed but pandas>=1.0.5 is required by {'neurom'}`) than `allensdk` (`error: pandas 1.1.2 is installed but pandas<=0.25.3,>=0.25.1 is required by {'allensdk'}`). I am stuck in a bit of a loop there. Any ideas? Sorry if my misunderstood things!

**Comment by FedeClaudi** [comment] 2020-09-14 06:54
mmm weird, which version of neurom are you installing? Maybe they released a new one that is not compatible with `allensdk`

**Comment by horsto** [comment] 2020-09-14 06:57
Neurom is installed together with brainrender and it jumps to `neurom-1.5.2` - should I downgrade?

**Comment by FedeClaudi** [comment] 2020-09-14 07:57
I have `neurom-1.4.20` which seems to install fine, so yeah maybe you can try that. `neurom` is only used in `morphapi` to reconstruct neurons morphologies anyways.

**Comment by horsto** [comment] 2020-09-14 13:26
Yes that fixed it indeed! Thanks! I think this can be closed.

**Comment by FedeClaudi** [comment] 2020-09-14 14:18
cool, thanks for checking!

**Comment by wisamreid** [comment] 2020-09-19 04:56
Hello!  I am excited to try this GUI out.  However, I get the same error discussed above when I run the "brainrender-gui" command.  I uninstalled the neurom-1.5.2 version of neurom and installed neurom-1.4.20 but it still doesn't work.  Any suggestions?  Anything you can do to help would be greatly appreciated.

**Comment by FedeClaudi** [comment] 2020-09-20 20:09
Hi, sorry for the late reply. 

Just to make sure, you're getting the same error about the pandas version during install right? 
Have you tried with an entirely new environment by any chance?
Any detail you might give me could help trying to find a solution.

**Comment by wisamreid** [comment] 2020-09-21 13:19
Hello, thanks for the reply.

Here is the output I am getting in my terminal for the "brainrender-gui" command:

allen mouse atlas (res. 25um)
From: http://www.brain-map.com (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/bg_atlasapi/structure_class.py", line 67, in __getitem__
    item = int(item)
ValueError: invalid literal for int() with base 10: 'root (997)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/brainrender-gui", line 8, in <module>
    sys.exit(clilaunch())
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/brainrender_gui/__init__.py", line 23, in clilaunch
    ex = App(atlas=atlas, axes=axes)
  File "/opt/anaconda3/lib/python3.7/site-packages/brainrender_gui/app.py", line 42, in __init__
    UI.__init__(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/brainrender_gui/ui.py", line 50, in __init__
    self.initUI()
  File "/opt/anaconda3/lib/python3.7/site-packages/brainrender_gui/ui.py", line 209, in initUI
    self.treeView = self.make_left_navbar()
  File "/opt/anaconda3/lib/python3.7/site-packages/brainrender_gui/ui.py", line 99, in make_left_navbar
    name = self.scene.atlas._get_from_structure(node.tag, "name")
  File "/opt/anaconda3/lib/python3.7/site-packages/bg_atlasapi/core.py", line 229, in _get_from_structure
    return self.structures[structure][key]
  File "/opt/anaconda3/lib/python3.7/site-packages/bg_atlasapi/structure_class.py", line 69, in __getitem__
    item = self.acronym_to_id_map[item]
KeyError: 'root (997)'

This seems like a similar error to what's being discussed here but I am not sure how to get around it.  I am happy to provide more info.  What would you like to know? Unfortunately, I don't have a way to try another environment at the moment.

**Comment by FedeClaudi** [comment] 2020-09-21 22:01
Hi, 

Okay so the problem you're having is not caused by `neurom` but it's something in either `bg-atlasapi` or `brainrender`.
Can you try upgrading both packages with:
```
pip install -U bg-atlasapi
```
and
```
pip install -U brainrender
```

and finally if you can let me know which versions you have of `bg-atlaspi`, `brainrender` and `bg-brainrender-gui` that should be enough for me to try and replicate (and fix) this bug on my machine.

**Comment by wisamreid** [comment] 2020-09-25 05:25
Thanks again for the reply.  I ran the update commands you mentioned but I seem to be in the same boat still.

Here are my current versions:

bg-atlasapi - Version: 0.2.0
bg-brainrender-gui - Version: 0.0.4
brainrender - Version: 1.0.0.0

Thank you,
--
Wisam

**Comment by FedeClaudi** [comment] 2020-09-25 07:57
I see, okay. Unfortunately I won't have time to look into this for a few days but I promise I'll try to address this issue as soon as I can. 
Perhaps @vigji can you have a look at it if you have some time ?

**Comment by vigji** [comment] 2020-09-25 09:53
Sorry for the late reply!
@wisamreid this problem has been fixed in the latest github commit; so you can temporarily fix it by reinstalling the module from GitHub.
@FedeClaudi we should just deploy a new version, how do you want to handle it?

**Comment by FedeClaudi** [comment] 2020-09-25 10:07
hey, what do you mean how do I want to handle it?

**Comment by vigji** [comment] 2020-09-25 13:15
atm there is no automatic version bumping nor travis deployment after testing (as is the case for bg-atlasapi); should I just manually change the third version number or the rc number and update to PyPI?

**Comment by FedeClaudi** [comment] 2020-09-25 13:25
yeah, I'm fine with that if you and @adamltyson are :)

**Closed as not planned** 2023-11-24 14:17 UTC
